# -*- coding: utf-8 -*-
"""AI ROBOT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rERRz8Szpt-kZ-FCprQ8ZuTp6YY_tdr8
"""

door_cost = {
    ("A", "B"): 1,
    ("B", "D"): 1,
    ("A", "C"): 5,
    ("C", "D"): 1,
    ("D", "G"): 1,
}
def path_cost(path):
    total = 0
    for i in range(len(path) - 1):
        door = (path[i], path[i+1])
        total = total + door_cost[door]
    return total

path1 = ["A", "B", "D", "G"]
path2 = ["A", "C", "D", "G"]

cost1 = path_cost(path1)
cost2 = path_cost(path2)

print("Path 1 (A -> B -> D -> G) Cost:", cost1)
print("Path 2 (A -> C -> D -> G) Cost:", cost2)

if cost1 < cost2:
    best_path = path1
    best_cost = cost1
else:
    best_path = path2
    best_cost = cost2

print("path1 cost:",cost1)
print("path2 cost:",cost2)
print()
print("cheapest path is :",best_path,"with cost",best_cost)
bfs_order=("A","G")
dfs_order=("A","G")
print("Results")
print("*"*40)
print("bfs(nearest first)checked :",len(bfs_order),"rooms",bfs_order)
print("dfs(deep first)checked :",len(dfs_order),"rooms",dfs_order)
print("cheapest path :",best_path,"with cost",best_cost)
print("*"*40)
print()
print("what we learned")
print("*BFS checks the nearest rooms first(spreds out).")
print("*DFS dives deep down one path first ")
print("cheapest path counts door cost")
door_cost[('A','B')]=4
door_cost[('A','C')]=1
Cost1=path_cost(path1)
Cost2=path_cost(path2)
print("path1 through B cost:",Cost1)
print("path2 through c cost:",Cost2)
if Cost1<Cost2:
    print("path1 is cheaper")
else:
    print("path2 is cheaper")
print("*"*40)